version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    volumes:
      - "jenkins_home:/var/jenkins_home"
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home:
    driver: local
